# Generated by Django 5.0.5 on 2024-05-07 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(default=datetime.date(2005, 1, 29)),
        ),
    ]
