# Generated by Django 4.1.13 on 2024-05-17 03:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_otp_id_alter_rooms_groupname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='temp_user',
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('c8b9a12f-f811-4253-bf0a-d5abd1c445b2'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('d5b12d24-6d17-4718-a11c-4081ef2e355d'), editable=False, max_length=120, unique=True),
        ),
    ]
