# Generated by Django 5.0.5 on 2024-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usermodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(default='media/user_profiles/profile.png', upload_to=''),
            preserve_default=False,
        ),
    ]
