# Generated by Django 4.1.13 on 2024-05-17 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_otp_temp_user_alter_otp_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='TempUser',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('4fc1e327-7417-408b-8460-47f7b0c3284b'), editable=False, max_length=120, unique=True),
        ),
    ]
