# Generated by Django 4.1.13 on 2024-05-17 03:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_otp_delete_tempuser_alter_rooms_groupname'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.CharField(default=uuid.UUID('54e5d812-728b-49d8-8593-f4f1696eab94'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('otp', models.BigIntegerField()),
                ('otp_datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('4cfe9e45-4d2d-429c-9d41-208e88231614'), editable=False, max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('stored_time', models.DateTimeField(auto_now=True)),
                ('dob', models.DateField()),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.otp')),
            ],
        ),
    ]
