# Generated by Django 5.0.5 on 2024-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usermodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(default='/user_profiles/profile.png', upload_to=''),
        ),
    ]
