# Generated by Django 4.1.13 on 2024-05-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_thread_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
