# Generated by Django 4.1.13 on 2024-05-17 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_otp_id_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('aed0b6ff-f555-4572-812b-3c6be89f6cb2'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('12ab3c98-ee86-412c-a09e-40dfd935ea4c'), editable=False, max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.otp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
