# Generated by Django 4.1.13 on 2024-05-17 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_otp_id_alter_rooms_groupname_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='sended_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('97df16f8-5087-4b45-82d8-83d079c872c0'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('df8ad2b8-c787-4a84-b214-112b170b927c'), editable=False, max_length=120, unique=True),
        ),
    ]
