# Generated by Django 4.1.13 on 2024-05-17 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_forgotpassword_sended_at_alter_otp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('230f4a7f-0946-48b1-a98c-ebbde496279b'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('9b45aab2-833e-408b-8445-130eddebb7c8'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('af1f2459-b028-4e1f-a0ac-a37f832ba13a'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('ea96f60a-9a04-4ab7-9d0e-4bf5e986a876'), editable=False, max_length=120, unique=True),
        ),
    ]
