# Generated by Django 4.1.13 on 2024-05-19 02:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_forgotpassword_secondary_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('62de41a3-a332-43b6-9209-512aada2ec14'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('12b4b4cd-9caf-48de-9055-3716bac1a292'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('42034097-8852-4d90-bdc3-43bd588f4d13'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('c1ce5ec4-fd85-4e06-b511-2f7c535302c5'), editable=False, max_length=120, unique=True),
        ),
    ]
