# Generated by Django 4.1.13 on 2024-05-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_rooms_delete_chatmessage_delete_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciver',
            new_name='receiver',
        ),
    ]
