# Generated by Django 4.1.13 on 2024-05-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_reciver_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.message'),
        ),
    ]
