# Generated by Django 4.1.13 on 2024-05-19 02:10

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tags_usermodel_banner_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='intresets',
            field=models.ManyToManyField(related_name='intresets', to='api.tags'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='supporters',
            field=models.ManyToManyField(related_name='supporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='supportings',
            field=models.ManyToManyField(related_name='supporting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('ed4faad6-2b39-4ff4-a137-1f4a537b4303'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('d0017376-3617-432c-a20b-cdc9adde89d5'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('50aee5ff-9f02-4f4b-8245-784259895ec4'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('e0d732b0-5533-4bb6-93cc-eb41b9d67667'), editable=False, max_length=120, unique=True),
        ),
    ]
