# Generated by Django 4.1.13 on 2024-05-14 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_rooms_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='users',
            field=models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
