# Generated by Django 4.1.13 on 2024-05-19 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usermodel_intresets_usermodel_supporters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='supporters',
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('8b40ea9c-0a35-4ae6-b378-a986c0d3bed7'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('c645e5d4-de6e-46fb-8ae4-abe6939f3d7a'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('98bee400-c71b-4538-9f34-7a7b028b9ad8'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('6adf054f-9ce0-4acb-a54c-ea5d5bbc9878'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='intresets',
            field=models.ManyToManyField(related_name='users', to='api.tags'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='supportings',
            field=models.ManyToManyField(related_name='supporters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
