# Generated by Django 4.1.13 on 2024-05-19 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_usermodel_supporters_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('b8864dd1-7a96-495c-8910-280b190b5c76'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('4cef40c3-a987-43bf-b0af-809577368756'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('ae9df636-dcab-4cdc-b434-22a562964ba2'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('61079617-6c5e-4ce6-b04e-ddbd5695f512'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
