# Generated by Django 4.1.13 on 2024-05-14 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_rooms_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='users',
        ),
        migrations.AddField(
            model_name='rooms',
            name='messages',
            field=models.ManyToManyField(null=True, related_name='messages', to='api.message'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='users',
            field=models.ManyToManyField(max_length=2, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
