# Generated by Django 4.1.13 on 2024-05-14 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_rooms_messages_remove_rooms_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
