# Generated by Django 4.1.13 on 2024-05-20 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('c664a6a5-bd36-4085-9e43-0fb3e785d1f2'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('85183a34-6642-40ff-8373-17b3df22ea4a'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('3bc59f36-227e-4004-b99d-1acf7e99abc5'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('c719a312-42ec-46e0-8157-ef604ad11c2c'), editable=False, max_length=120, unique=True),
        ),
    ]
