# Generated by Django 4.1.13 on 2024-05-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='users',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
