# Generated by Django 4.1.13 on 2024-05-20 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='intresets',
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('ac2ccf5a-9038-4c3b-bb38-dfd2003a46ea'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('97a7bd9a-4fd0-423e-9993-e61f26abd36a'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('3fde361a-fac5-4eb2-80cc-4a2419ecf666'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('691bfc5d-f983-4299-8813-15ad7cb174ab'), editable=False, max_length=120, unique=True),
        ),
    ]
