# Generated by Django 4.1.13 on 2024-05-20 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_usermodel_intresets_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='intresets',
            field=models.ManyToManyField(related_name='users', to='api.tags'),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('e7a92a2d-8c8b-4bca-b672-f2ec30128654'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('ad2008a4-e5b5-4e14-86a6-2ce090ffd76e'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('ee0f701a-da6a-4357-a7e8-257d7e64b5e2'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('a21fa7c0-bbf7-49df-8ee4-c0a8481ea133'), editable=False, max_length=120, unique=True),
        ),
    ]
