# Generated by Django 4.1.13 on 2024-05-20 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_usermodel_intresets_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('ec7f4af4-317e-4874-9bed-a56f1690bbf8'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('d3929d2d-dd37-4679-a36e-172305435806'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('2bf97346-f100-41cd-acab-8c018e45d280'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('6b20c177-ca2b-468c-9056-205b8284f5bb'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
