# Generated by Django 4.1.13 on 2024-05-14 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.UUIDField(default=uuid.UUID('9d21bec8-e1db-40ef-b4de-dfcd03d661ad'), editable=False, unique=True),
        ),
    ]
