# Generated by Django 4.1.13 on 2024-05-20 04:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('3695279e-26bb-456d-b8ff-5218e89cd381'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('f0ebaea8-420e-4b9e-b63a-a2cfd415011e'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('abae421f-1b48-4449-a738-d4e7cd087e8a'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('ee1d09a5-03a0-40c4-aeef-ae0e6014f22a'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(default='/user_profiles/profile.png', upload_to='user_profiles'),
        ),
    ]
