# Generated by Django 4.1.13 on 2024-05-14 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('079a0c4a-d17f-4fd5-bf3e-05d1992f82d0'), editable=False, max_length=120, unique=True),
        ),
    ]
