# Generated by Django 4.1.13 on 2024-05-14 14:15

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 14, 15, 31, 961894)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('74dfebb6-2a6e-4c46-a00e-7e4dcadc625f'), editable=False, max_length=120, unique=True),
        ),
    ]
