# Generated by Django 4.1.13 on 2024-05-20 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('f941d0a0-545a-4607-8648-e12ab5dbcd8d'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('3cbc5389-5869-4ec9-9c2f-56ddd88cf4c7'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('9e62cf32-f9ad-4ade-ba0f-8d700096fd49'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('f448f745-d04c-4f23-9e9a-d118a6c376b7'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(default='/media/user_profiles/profile.png', upload_to='user_profiles'),
        ),
    ]
