# Generated by Django 4.1.13 on 2024-05-14 14:16

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_message_sended_at_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 14, 16, 37, 606715)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('f27015ea-ec42-4fca-b6c6-57fcc7a5cbf1'), editable=False, max_length=120, unique=True),
        ),
    ]
