# Generated by Django 4.1.13 on 2024-05-14 14:16

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_message_sended_at_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 14, 16, 40, 500395)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('ed06a745-6c2d-44dd-853d-3b864ea622f1'), editable=False, max_length=120, unique=True),
        ),
    ]
