# Generated by Django 4.1.13 on 2024-05-20 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_posts_tags_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('39817575-4d50-44bc-be45-d425362b670a'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('510802cb-7539-48c9-b723-9a25a6f8a063'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('29f66e8e-c0ca-4196-a341-b6fc6615d06a'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.CharField(default=uuid.UUID('6a0d4af8-98af-469a-aecb-6c66d9ab1d59'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('63d436d6-876a-418a-b1c1-1aa001216384'), editable=False, max_length=120, unique=True),
        ),
    ]
