# Generated by Django 4.1.13 on 2024-05-20 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('ad3d17d4-118e-46d9-aa45-94e41a334060'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('812a3a16-6991-44e2-81ee-02e0b26e2d2e'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('e21b50b1-87cd-463f-8b91-b59c2bc4f4f3'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('17241b48-5201-4878-8727-28c9e0ecfdfa'), editable=False, max_length=120, unique=True),
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
