# Generated by Django 4.1.13 on 2024-05-14 14:16

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_message_sended_at_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 14, 16, 48, 607567)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('ff6f791a-6edc-4db7-bc20-006ccb43dae0'), editable=False, max_length=120, unique=True),
        ),
    ]
