# Generated by Django 4.1.13 on 2024-05-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('bdb80bb5-96d8-49ff-9060-5584c44d4ea6'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('bde28677-2413-4a0b-82a7-763bb3dbce38'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('7a76cbef-811c-46b2-8e87-eb1b9b494da1'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('a089f999-786d-4fd0-a92b-628bcebeec2a'), editable=False, max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.CharField(default=uuid.UUID('f3db16fd-7989-4dde-849d-c4c40bef139d'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('content', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('tags', models.ManyToManyField(related_name='posts', to='api.tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
