# Generated by Django 4.1.13 on 2024-05-14 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_message_sended_at_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('fea88875-79f3-4f44-bdbd-e10d6101a0b0'), editable=False, max_length=120, unique=True),
        ),
    ]
