# Generated by Django 4.1.13 on 2024-05-14 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_message_sended_at_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('5e4b5f39-30e9-474a-bf9f-dc6e939f2e91'), editable=False, max_length=120, unique=True),
        ),
    ]
