# Generated by Django 4.1.13 on 2024-05-20 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('2f3fe6c5-351e-44f1-93c6-d24be3576be8'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('9e2bed31-71d1-45dc-bf53-63ac77ff1a8c'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('2b5eb22b-784a-4ff5-8ba4-341aaf34f482'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.CharField(default=uuid.UUID('c49a4382-5d40-4c7a-a725-0a05cfbddee3'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('808375e4-12cb-4b5f-8380-fa68422b1886'), editable=False, max_length=120, unique=True),
        ),
    ]
