# Generated by Django 4.1.13 on 2024-05-14 14:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 14, 22, 53, 674611)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('fa6232b2-4737-40f4-81e3-f484dfb84aba'), editable=False, max_length=120, unique=True),
        ),
    ]
