# Generated by Django 4.1.13 on 2024-05-20 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_posts_tags_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='api.tags'),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('7d774fdc-d65e-4282-a869-a9f06e924365'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('ad7c9197-153e-40f5-8215-8d37355c48e8'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('505c2c9d-1664-48be-8e00-8aa9f496a642'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.CharField(default=uuid.UUID('fd566f02-61dd-4ae2-8650-363320f4bf93'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('8f000e9f-74d7-4c7d-92f2-a2229141eaca'), editable=False, max_length=120, unique=True),
        ),
    ]
