# Generated by Django 4.1.13 on 2024-05-15 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_message_sended_at_alter_rooms_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('ff5351ef-4d49-44e1-9cac-ded48468403d'), editable=False, max_length=120, unique=True),
        ),
    ]
