# Generated by Django 4.1.13 on 2024-05-22 03:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_forgotpassword_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='id',
            field=models.CharField(default=uuid.UUID('78d5c4db-3d96-452c-b60c-200d15b7cccf'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='secondary_code',
            field=models.CharField(default=uuid.UUID('1db08117-c9a4-41f1-9600-d2ea68e4a78d'), editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('a38737dd-1954-4adc-85c8-386a786cdbf0'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.CharField(default=uuid.UUID('04774a32-8ab8-4702-8d7a-6ce1a393af60'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('d171e085-91d1-44c1-a3e6-424b04c4fcac'), editable=False, max_length=120, unique=True),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
