# Generated by Django 4.1.13 on 2024-05-15 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_tempuser_alter_rooms_groupname_alter_usermodel_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.CharField(default=uuid.UUID('31dfefe3-183a-4fad-b93c-1d8dc9de56a6'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('otp', models.BigIntegerField()),
                ('otp_datetime', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('a3308d82-70a6-48f6-8bc4-671a29727f7c'), editable=False, max_length=120, unique=True),
        ),
    ]
