# Generated by Django 4.1.13 on 2024-05-15 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_user_id_otp_temp_user_alter_otp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('8447f804-aab3-4c3c-ab8a-17ea0466bb5b'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='groupName',
            field=models.CharField(default=uuid.UUID('3f3c2688-81c1-44ed-bc70-e1e1477cfc75'), editable=False, max_length=120, unique=True),
        ),
    ]
